version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://66.97.43.140:4000"