version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://168.181.187.43:4000"