version: "3.3"

services:
  app:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5000:3000"
    environment:
      REACT_APP_API_BASE_URL: "https://api.ianrodriguezprop.com"
    command: npx -y serve build